"use client";
import { useState } from "react";
import { AlertCircle, CheckCircle2, Loader2, Mail, MapPin, Phone, Send } from "lucide-react";

const inputClass = "w-full border border-black/15 bg-white px-4 py-3 text-black outline-none placeholder:text-black/35 focus:border-[#DA291C] disabled:opacity-50";
export default function ContactPage() {
  const [submitting, setSubmitting] = useState(false); const [status, setStatus] = useState<"idle" | "success" | "error">("idle");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); setStatus("idle"); const form = event.currentTarget; const data = Object.fromEntries(new FormData(form)); try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); if (!response.ok) throw new Error(); setStatus("success"); form.reset(); } catch { setStatus("error"); } finally { setSubmitting(false); } }
  return <main className="min-h-screen bg-white"><section className="border-b border-black/10 bg-black px-6 py-20 text-white"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#DA291C]">Birlikte üretelim</p><h1 className="mt-5 text-4xl font-bold tracking-[-0.04em] md:text-6xl">İletişim</h1><p className="mt-6 max-w-2xl text-base leading-7 text-[#B7B7B7]">3D baskı, endüstriyel tasarım ve üretim ihtiyaçlarınız için ekibimize ulaşın.</p></div></section><div className="mx-auto grid max-w-7xl gap-12 px-6 py-14 lg:grid-cols-[1.5fr_1fr]"><form onSubmit={submit} className="border border-black/10 p-6 sm:p-9"><h2 className="text-2xl font-bold">Mesaj gönderin</h2><div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Adınız Soyadınız<input className={`${inputClass} mt-2`} name="name" required disabled={submitting} /></label><label className="text-sm font-bold">E-posta<input className={`${inputClass} mt-2`} type="email" name="email" required disabled={submitting} /></label></div><label className="mt-5 block text-sm font-bold">Konu<input className={`${inputClass} mt-2`} name="subject" required disabled={submitting} /></label><label className="mt-5 block text-sm font-bold">Mesajınız<textarea className={`${inputClass} mt-2 min-h-36 resize-y`} name="message" required disabled={submitting} /></label>{status === "success" && <p className="mt-5 flex gap-2 border border-black/10 bg-black/[0.03] p-4 text-sm"><CheckCircle2 className="h-5 w-5 text-[#DA291C]" />Mesajınız başarıyla gönderildi.</p>}{status === "error" && <p className="mt-5 flex gap-2 border border-[#DA291C] bg-[#DA291C]/5 p-4 text-sm text-[#DA291C]"><AlertCircle className="h-5 w-5" />Bir hata oluştu. Lütfen tekrar deneyin.</p>}<button disabled={submitting} className="mt-6 inline-flex items-center gap-2 bg-[#DA291C] px-7 py-3.5 text-sm font-bold text-white hover:bg-black disabled:opacity-50">{submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}{submitting ? "Gönderiliyor" : "Mesajı Gönder"}</button></form><aside className="bg-black p-8 text-white"><h2 className="text-2xl font-bold">Bize ulaşın</h2><div className="mt-8 space-y-7 text-sm text-[#B7B7B7]"><div className="flex gap-4"><MapPin className="h-5 w-5 shrink-0 text-[#DA291C]" /><p>Acıbadem Mahallesi, Akçaağaç Sokak No: 8<br />Üsküdar / İstanbul</p></div><a href="tel:+905465868005" className="flex gap-4 hover:text-white"><Phone className="h-5 w-5 text-[#DA291C]" />0546 586 80 05</a><a href="mailto:info@kesiolabs.com" className="flex gap-4 hover:text-white"><Mail className="h-5 w-5 text-[#DA291C]" />info@kesiolabs.com</a></div></aside></div></main>;
}
