import type { Metadata } from "next";
import { ExternalLink } from "lucide-react";
import { getRepresentativeGroups, getRepresentatives } from "@/lib/strapi";

export const metadata: Metadata = { title: "Temsilcilikler", description: "Kesiolabs temsilcilik ve teknoloji partnerleri.", alternates: { canonical: "/temsilcilikler" } };

export default async function RepresentativesPage() {
  const [groups, representatives] = await Promise.all([getRepresentativeGroups(), getRepresentatives()]);
  const sections = groups.length ? groups.map((group) => ({ group, items: representatives.filter((item) => item.groupSlug === group.slug) })) : [{ group: null, items: representatives }];
  return <main className="min-h-screen bg-white"><section className="border-b border-black/10 bg-black px-6 py-20 text-white"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#DA291C]">Teknoloji ağı</p><h1 className="mt-5 text-4xl font-bold tracking-[-0.04em] md:text-6xl">Temsilcilikler</h1><p className="mt-6 max-w-2xl text-base leading-7 text-[#B7B7B7]">Endüstriyel teknoloji çözümlerimizi güçlendiren marka ve iş ortaklarımızı keşfedin.</p></div></section><div className="mx-auto max-w-7xl px-6 py-14">{representatives.length ? <div className="space-y-16">{sections.map(({ group, items }) => items.length ? <section key={group?.slug ?? "all"}><div className="mb-7 flex items-end justify-between border-b border-black/10 pb-4"><h2 className="text-2xl font-bold">{group?.title ?? "Temsilcilikler"}</h2><span className="text-xs font-bold text-black/45">{items.length} marka</span></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <article key={item.id} className="flex min-h-72 flex-col border border-black/10 bg-white p-6 hover:shadow-[0_18px_45px_rgba(0,0,0,0.08)]"> <div className="flex h-24 items-center justify-center bg-black/[0.025] p-4">{item.logo ? <img src={item.logo} alt={`${item.name} logo`} className="max-h-full max-w-full object-contain" /> : <span className="text-sm font-bold text-black/40">{item.name}</span>}</div><h3 className="mt-6 text-xl font-bold">{item.name}</h3><p className="mt-3 flex-1 text-sm leading-6 text-black/60">{item.shortDescription}</p>{item.website && <a href={item.website} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#DA291C] hover:text-black">Web sitesini ziyaret et <ExternalLink className="h-4 w-4" /></a>}</article>)}</div></section> : null)}</div> : <div className="border border-dashed border-[#B7B7B7] bg-black/[0.02] px-6 py-20 text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#DA291C]">İçerik hazırlanıyor</p><h2 className="mt-4 text-2xl font-bold">Temsilcilik bilgileri yakında burada olacak.</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-black/55">CMS altyapısı hazır. Yayınlanan temsilcilik ve gruplar otomatik olarak bu sayfada görünecek.</p></div>}</div></main>;
}
