import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { getCategoryTitle, getMediaUrl, getPosts, type StrapiPost } from "@/lib/strapi";

const labels = { article: "Makale", news: "Haber", "application-note": "Uygulama Notu" } as const;

function formatDate(value?: string) { return value ? new Intl.DateTimeFormat("tr-TR", { day: "numeric", month: "long", year: "numeric" }).format(new Date(value)) : ""; }

export default async function ArticleListing({ type, title, intro }: { type?: StrapiPost["articleType"]; title: string; intro: string }) {
  const allPosts = await getPosts();
  const posts = type ? allPosts.filter((post) => post.articleType === type) : allPosts;
  const featured = posts[0]; const rest = featured ? posts.slice(1) : [];
  return <main className="min-h-screen bg-white"><section className="border-b border-black/10 bg-black px-6 py-20 text-white"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#DA291C]">Bilgi merkezi</p><h1 className="mt-5 text-4xl font-bold tracking-[-0.04em] md:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-[#B7B7B7]">{intro}</p><nav className="mt-9 flex flex-wrap gap-2" aria-label="Makale türleri"><Link href="/makaleler" className="border border-white/25 px-4 py-2 text-sm font-bold hover:bg-white hover:text-black">Tüm Makaleler</Link><Link href="/makaleler/haberler" className="border border-white/25 px-4 py-2 text-sm font-bold hover:bg-white hover:text-black">Haberler</Link><Link href="/makaleler/uygulama-notlari" className="border border-white/25 px-4 py-2 text-sm font-bold hover:bg-white hover:text-black">Uygulama Notları</Link></nav></div></section><div className="mx-auto max-w-7xl px-6 py-14">{featured ? <><Link href={`/makaleler/${featured.slug}`} className="group grid overflow-hidden border border-black/10 lg:grid-cols-[1.15fr_1fr]"><div className="aspect-[16/10] overflow-hidden bg-black/[0.03] lg:aspect-auto">{getMediaUrl(featured.coverImage) && <img src={getMediaUrl(featured.coverImage)!} alt={featured.title} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.02]" />}</div><div className="flex flex-col justify-center p-8 lg:p-12"><div className="flex flex-wrap gap-3 text-xs font-bold uppercase tracking-[0.14em] text-[#DA291C]"><span>{featured.articleType ? labels[featured.articleType] : "Makale"}</span><span className="text-black/35">{getCategoryTitle(featured.category)}</span></div><h2 className="mt-5 text-3xl font-bold tracking-[-0.03em] group-hover:text-[#DA291C]">{featured.title}</h2><p className="mt-4 text-sm leading-7 text-black/60">{featured.excerpt}</p><time className="mt-7 text-xs font-bold text-black/45">{formatDate(featured.date)}</time></div></Link><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{rest.map((post) => <ArticleCard key={post.id} post={post} />)}</div></> : <div className="border border-dashed border-[#B7B7B7] bg-black/[0.02] px-6 py-20 text-center"><h2 className="text-2xl font-bold">Bu bölümde henüz yayın yok.</h2><p className="mt-3 text-sm text-black/55">Yeni içerikler CMS üzerinden yayınlandığında otomatik olarak burada görünecek.</p></div>}</div></main>;
}

function ArticleCard({ post }: { post: StrapiPost }) { const image = getMediaUrl(post.coverImage); return <article className="group flex flex-col border border-black/10 bg-white"><Link href={`/makaleler/${post.slug}`} className="aspect-[16/10] overflow-hidden bg-black/[0.03]">{image && <img src={image} alt={post.title} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.03]" />}</Link><div className="flex flex-1 flex-col p-6"><div className="flex justify-between gap-3 text-[11px] font-bold uppercase tracking-[0.13em] text-[#DA291C]"><span>{post.articleType ? labels[post.articleType] : "Makale"}</span><time className="text-black/40">{formatDate(post.date)}</time></div><h2 className="mt-4 text-xl font-bold leading-tight"><Link href={`/makaleler/${post.slug}`} className="hover:text-[#DA291C]">{post.title}</Link></h2><p className="mt-3 flex-1 text-sm leading-6 text-black/60 line-clamp-3">{post.excerpt}</p><Link href={`/makaleler/${post.slug}`} className="mt-6 inline-flex items-center justify-between border-t border-black/10 pt-4 text-sm font-bold">Devamını Oku <ArrowUpRight className="h-4 w-4 text-[#DA291C]" /></Link></div></article>; }
