import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import sanitizeHtml from "sanitize-html";
import { ArrowLeft, Calendar } from "lucide-react";
import { getCategoryTitle, getMediaUrl, getPostBySlug, getPosts } from "@/lib/strapi";

const typeLabels: Record<string, string> = { article: "Makale", news: "Haber", "application-note": "Uygulama Notu" };
function dateTR(value?: string) { return value ? new Intl.DateTimeFormat("tr-TR", { day: "numeric", month: "long", year: "numeric" }).format(new Date(value)) : ""; }
function safeContent(value: unknown) { if (typeof value !== "string") return ""; return sanitizeHtml(value, { allowedTags: sanitizeHtml.defaults.allowedTags.concat(["img", "h1", "h2"]), allowedAttributes: { a: ["href", "target", "rel"], img: ["src", "alt", "title", "width", "height"] }, transformTags: { a: sanitizeHtml.simpleTransform("a", { target: "_blank", rel: "noopener noreferrer" }) } }); }

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const post = await getPostBySlug(slug); if (!post) return { title: "Makale bulunamadı" }; const image = getMediaUrl(post.coverImage); return { title: post.title, description: post.excerpt, alternates: { canonical: `/makaleler/${slug}` }, openGraph: { title: post.title, description: post.excerpt, type: "article", images: image ? [image] : [] } }; }

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const post = await getPostBySlug(slug); if (!post) notFound(); const all = await getPosts(); const related = all.filter((item) => item.slug !== slug).slice(0, 3); const image = getMediaUrl(post.coverImage); const html = safeContent(post.contentBlocks);
  return <main className="min-h-screen bg-white"><article><header className="border-b border-black/10 bg-black px-6 py-16 text-white"><div className="mx-auto max-w-4xl"><Link href="/makaleler" className="inline-flex items-center gap-2 text-sm font-bold text-[#B7B7B7] hover:text-white"><ArrowLeft className="h-4 w-4" />Makalelere dön</Link><div className="mt-10 flex flex-wrap gap-3 text-xs font-bold uppercase tracking-[0.16em] text-[#DA291C]"><span>{post.articleType ? typeLabels[post.articleType] : "Makale"}</span>{getCategoryTitle(post.category) && <span className="text-[#B7B7B7]">{getCategoryTitle(post.category)}</span>}</div><h1 className="mt-5 text-4xl font-bold leading-[1.08] tracking-[-0.04em] md:text-6xl">{post.title}</h1><p className="mt-6 text-lg leading-8 text-[#B7B7B7]">{post.excerpt}</p><div className="mt-8 flex items-center gap-2 text-sm text-[#B7B7B7]"><Calendar className="h-4 w-4 text-[#DA291C]" /><time>{dateTR(post.date)}</time></div></div></header>{image && <div className="mx-auto max-w-6xl px-6 pt-10"><img src={image} alt={post.title} className="max-h-[620px] w-full object-cover" /></div>}<div className="mx-auto max-w-3xl px-6 py-14"><div className="article-content" dangerouslySetInnerHTML={{ __html: html || `<p>${post.excerpt ?? ""}</p>` }} /></div></article>{related.length > 0 && <section className="border-t border-black/10 bg-black/[0.025] px-6 py-14"><div className="mx-auto max-w-6xl"><h2 className="text-2xl font-bold">Diğer Makaleler</h2><div className="mt-7 grid gap-4 md:grid-cols-3">{related.map((item) => <Link key={item.slug} href={`/makaleler/${item.slug}`} className="border border-black/10 bg-white p-5 font-bold leading-6 hover:border-[#DA291C] hover:text-[#DA291C]">{item.title}</Link>)}</div></div></section>}</main>;
}
